name: Test and Static Analysis

on:
  - push
  - pull_request

jobs:
  test-and-static-analysis:
    name: Test and Static Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          tools: composer:v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Composer JSON
        run: composer validate

      - name: Run Composer
        run: composer install --no-interaction

      - name: PHP Lint
        run: ./vendor/bin/parallel-lint src tests

      - name: Unit tests
        run: |
          mkdir -p build/logs
          ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml

      - name: PHP Code Sniffer
        run: ./vendor/bin/phpcs --ignore=vendor --standard=coding_standard.xml -s .

      - name: Code Coverage (Coveralls)
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php vendor/bin/php-coveralls -v
